# -*- coding: utf-8 -*-
"""MLforPP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zHHnkZF8FVCj6he_9fMeMuJhTPpat__

Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Importing the dataset"""

dataset = pd.read_csv('PrivacyPolicy.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(x)

print(y)

"""Encoding the categorical data"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers= [('Encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print(x)

"""Splitting the data into the Training Set and Testing Set"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.5, random_state = 0)

print(x_train)
print(x_test)
print(y_train)
print(y_test)

"""Multiple Linear Regression model"""

from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(x_train, y_train)

"""Predicting the Test set results"""

y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1),y_test.reshape(len(y_test), 1)), 1))